import * as Crypto from "expo-crypto";

import type { SecureStorage } from "../secure-storage/secure-storage";
import { createDatabaseKeyProvider, type DatabaseKeyProvider } from "./database-key";

/**
 * The device's cryptographic random source.
 *
 * `expo-crypto`'s `getRandomBytesAsync` is backed by the platform CSPRNG.
 * `Math.random()` is never acceptable here and is not merely discouraged — it is
 * seeded predictably and would make the database key guessable.
 *
 * Note for anyone debugging a test: under Jest this returns **zeroes**.
 * `expo-crypto`'s autogenerated mock implements `getRandomValues` as a no-op, so
 * the buffer is never filled. `createDatabaseKeyProvider` rejects an all-zero
 * buffer, which is why that guard exists rather than being theoretical.
 */
export function expoRandomBytes(byteCount: number): Promise<Uint8Array> {
  return Crypto.getRandomBytesAsync(byteCount);
}

/** The database key provider the app uses, wired to the platform CSPRNG. */
export function createExpoDatabaseKeyProvider(secureStorage: SecureStorage): DatabaseKeyProvider {
  return createDatabaseKeyProvider({ secureStorage, randomBytes: expoRandomBytes });
}
