import * as Crypto from "expo-crypto";

import { createInMemorySecureStorage } from "@tests/mocks/secure-storage";

import { DatabaseKeyError } from "@/core/security/database-key/database-key";
import {
  createExpoDatabaseKeyProvider,
  expoRandomBytes,
} from "@/core/security/database-key/expo-database-key";

jest.mock("expo-crypto", () => ({ getRandomBytesAsync: jest.fn() }));

const getRandomBytesAsync = jest.mocked(Crypto.getRandomBytesAsync);

describe("expoRandomBytes", () => {
  it("draws from expo-crypto's CSPRNG for the requested count", async () => {
    getRandomBytesAsync.mockResolvedValue(new Uint8Array(32).fill(7));

    await expect(expoRandomBytes(32)).resolves.toHaveLength(32);
    expect(getRandomBytesAsync).toHaveBeenCalledWith(32);
  });
});

describe("createExpoDatabaseKeyProvider", () => {
  it("produces a key in the format the SQLCipher adapter accepts", async () => {
    getRandomBytesAsync.mockResolvedValue(
      Uint8Array.from({ length: 32 }, (_unused, index) => index + 1),
    );
    const secureStorage = createInMemorySecureStorage();

    const key = await createExpoDatabaseKeyProvider(secureStorage).get();

    // Same expression `sqlcipher-database.ts` validates against, so the two
    // ends of the key's journey are asserted to agree.
    expect(key).toMatch(/^[0-9a-f]{64}$/);
    await expect(secureStorage.get("database.key")).resolves.toBe(key);
  });

  /**
   * Worth an explicit test because it is the one place the guard has ever
   * actually fired: `expo-crypto`'s autogenerated Jest mock implements
   * `getRandomValues` as a no-op returning `null`, so the real
   * `getRandomBytesAsync` hands back a buffer of zeroes under Jest. A provider
   * that trusted its random source would have quietly produced a database
   * encrypted with 32 zero bytes.
   */
  it("refuses the all-zero buffer a stubbed CSPRNG returns", async () => {
    getRandomBytesAsync.mockResolvedValue(new Uint8Array(32));

    await expect(
      createExpoDatabaseKeyProvider(createInMemorySecureStorage()).get(),
    ).rejects.toThrow(DatabaseKeyError);
  });
});
